version: '3.1'

services:

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: blog
    volumes:
      - /c/mysqlVolume/mysql:/var/lib/mysql
    ports:
      - 3306:3306
      